### PR TITLE
exclude deleted annotations from csv download

### PR DESCRIPTION
**Pull request by cofiem**
see #302

### CODE REVIEW

**Comment by atruskie** [comment]
Looks good.

My only question: Does doing the deleted check like I did in https://github.com/QutBioacoustics/baw-server/blob/b6b48089a1f790a3d2874fe4d8137dcc0d4f0d0b/app/models/analysis_jobs_item.rb#L159 offer any real advantages?

**Comment by cofiem** [comment]
Well, firstly, the comment "cast back to active record relation" is misleading - it isn't a cast, it's using the ActiveRecord [`from`](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-from) with the Arel query as the query.

I think you need line 160. Without line 160 (`query.joins(:audio_recording)`), you wouldn't get the ActiveRecord scope, you'd only have the `from` subquery, so line 160 is necessary, yes.

**Comment by atruskie** [comment]
I meant, for using in this fix... All the default scopes should be used, if they were this bug (#302) wouldn't have happened...

**Comment by cofiem** [comment]
Oh, righto. I'm not sure. The Arel query might be too complex to be able to make use of ActiveRecord for parts of it. It's a good thought, tho.

**Comment by JessCappadonna** [comment]
Hi guys, 
I am soooo excited this is happening. One thing I am wondering, can we still see deleted things if we want too? I was envisioning having a way to filter them out/sort, rather then deleting them all together. This isn't critical, but would be helpful to know if one person is changing what another has done.

**Comment by atruskie** [comment]
@JessCappadonna this changeset will remain scoped to fixing the bug only (many small changes increase the speed at which we can ship fixes),  however, I've taken your comment and integrated it into ideas we have discussed previously. You can comment and review here: https://github.com/QutBioacoustics/baw-server/issues/311

**Comment by atruskie** [comment]
This is ready to merge.

I have an idea to improve it. If I find the time before deploy I will experiment, otherwise, I'll merge.

**Pull request merged**
