### PR TITLE
Allow per project access for anonymous and logged-in users

### LINKED ISSUE #99: Broader Permission categories for Projects (and all sub-securables)
Two new permissions:

- Logged-in access
    - should be able to `read`, `write`, but not `own`
- Anonymous access
   - should be able to `read`, `write`, but not `own`

- Only owners/creators can modify the above permissions

### PR DESCRIPTION
**Pull request by cofiem**
Closes #99 

See also https://github.com/QutBioacoustics/baw-server/wiki/Permissions

### CODE REVIEW

**Comment by atruskie** [comment]
I think it will be prudent to squash these commits before we do the final merge.

**Comment by cofiem** [comment]
The commit https://github.com/QutBioacoustics/baw-server/pull/265/commits/0f183da545ad798db2fa4c582db119b5841153e9 is the one to test on staging...

**Comment by atruskie** [comment]
@cofiem - we did a review of the changes. They seem to work well. Lots of positive feedback.

There were some design comments. I've written up the notes. There's a little bit of work to be done around naming and word choices. See https://github.com/QutBioacoustics/Ecoacoustics/blob/master/Design%20documents/Permissions%20Feedback.md

**Comment by cofiem** [comment]
Commits squashed, and develop merged in. This branch is ready to be merged with develop.

**Comment by cofiem** [comment]
Woot! :rocket:

**Pull request merged**
